name: food_recipes_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  vexana: ^5.0.1
  awesome_dialog: ^3.2.1
  flutter_feather_icons: ^2.0.0+1
  fluttertoast: ^8.2.8
  hive: ^2.2.3
  flutter_keyboard_visibility: ^6.0.0
  flutter_svg: ^2.0.15
  path_provider: ^2.1.5
  flutter_localization: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/png/
    - assets/png/flags/
